import React, { useEffect, useState } from 'react';
import {
  Typography, Box, Paper, Button, Table, TableHead, TableRow,
  TableCell, TableBody, MenuItem, TextField, CircularProgress, Alert,
} from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import AddIcon from '@mui/icons-material/Add';
import apiClient from '../api/client';

const REPORT_TYPES = [
  { value: 'ONBOARDING_SUMMARY', label: 'Onboarding Summary' },
  { value: 'OFFBOARDING_SUMMARY', label: 'Offboarding Summary' },
  { value: 'ACCESS_AUDIT', label: 'Access Audit' },
  { value: 'TASK_STATUS', label: 'Task Status Report' },
  { value: 'FULL_AUDIT', label: 'Full Audit Export' },
];

export default function ReportGeneration() {
  const [reports, setReports] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [form, setForm] = useState({ type: '', start_date: '', end_date: '', department_id: '' });
  const [success, setSuccess] = useState('');

  useEffect(() => {
    Promise.all([
      apiClient.get('/reports'),
      apiClient.get('/mappings/departments'),
    ]).then(([r, d]) => {
      setReports(r.data || []);
      setDepartments(d.data || []);
    }).catch(() => {}).finally(() => setLoading(false));
  }, []);

  async function handleGenerate() {
    if (!form.type) return;
    setGenerating(true);
    try {
      const body = { type: form.type };
      if (form.start_date) body.start_date = form.start_date;
      if (form.end_date) body.end_date = form.end_date;
      if (form.department_id) body.department_id = form.department_id;
      await apiClient.post('/reports/generate', body);
      setSuccess('Report queued. Download using the button below.');
      const res = await apiClient.get('/reports');
      setReports(res.data || []);
    } catch {
      setSuccess('');
    } finally {
      setGenerating(false);
    }
  }

  function downloadReport(r) {
    const token = localStorage.getItem('token');
    fetch(`http://localhost:4000/api/reports/${r.id}/download`, {
      headers: { Authorization: `Bearer ${token}` },
    }).then((res) => res.blob()).then((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `report-${r.id}-${r.type}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    });
  }

  return (
    <Box>
      <Typography variant="h4" gutterBottom>Report Generation</Typography>

      {success && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setSuccess('')}>{success}</Alert>}

      <Paper sx={{ p: 3, mb: 3 }}>
        <Typography variant="h6" gutterBottom>Generate New Report</Typography>
        <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <TextField
            select label="Report Type" value={form.type}
            onChange={(e) => setForm({ ...form, type: e.target.value })}
            sx={{ minWidth: 220 }} size="small"
          >
            {REPORT_TYPES.map((t) => (
              <MenuItem key={t.value} value={t.value}>{t.label}</MenuItem>
            ))}
          </TextField>
          <TextField
            label="Start date" type="date" size="small" value={form.start_date}
            onChange={(e) => setForm({ ...form, start_date: e.target.value })}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="End date" type="date" size="small" value={form.end_date}
            onChange={(e) => setForm({ ...form, end_date: e.target.value })}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            select label="Department (optional)" value={form.department_id}
            onChange={(e) => setForm({ ...form, department_id: e.target.value })}
            sx={{ minWidth: 200 }} size="small"
          >
            <MenuItem value="">All departments</MenuItem>
            {departments.map((d) => <MenuItem key={d.id} value={d.id}>{d.name}</MenuItem>)}
          </TextField>
          <Button
            variant="contained" startIcon={<AddIcon />}
            onClick={handleGenerate} disabled={!form.type || generating}
          >
            {generating ? 'Generating...' : 'Generate'}
          </Button>
        </Box>
      </Paper>

      <Paper>
        <Box sx={{ p: 2 }}>
          <Typography variant="h6">Report History</Typography>
        </Box>
        {loading ? (
          <Box sx={{ p: 4, textAlign: 'center' }}><CircularProgress /></Box>
        ) : (
          <Table size="small">
            <TableHead>
              <TableRow>
                <TableCell>Type</TableCell>
                <TableCell>Generated By</TableCell>
                <TableCell>Date Range</TableCell>
                <TableCell>Created</TableCell>
                <TableCell align="right">Download</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {reports.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} align="center" sx={{ color: 'text.secondary' }}>
                    No reports generated yet
                  </TableCell>
                </TableRow>
              ) : (
                reports.map((r) => (
                  <TableRow key={r.id} hover>
                    <TableCell>{r.type}</TableCell>
                    <TableCell>{r.generated_by}</TableCell>
                    <TableCell sx={{ fontSize: '0.8rem', color: 'text.secondary' }}>
                      {r.start_date || r.end_date
                        ? `${r.start_date || '?'} → ${r.end_date || '?'}`
                        : 'All time'}
                    </TableCell>
                    <TableCell>{new Date(r.created_at).toLocaleString()}</TableCell>
                    <TableCell align="right">
                      <Button size="small" startIcon={<DownloadIcon />} onClick={() => downloadReport(r)}>
                        Download
                      </Button>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        )}
      </Paper>
    </Box>
  );
}
